import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Bebas_Neue } from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
// import { SessionProvider } from "next-auth/react";
// import { auth } from "@/auth";

const inter = Inter({ subsets: ['latin'] })
const bebas = Bebas_Neue({ subsets: ['latin'], weight: ['400'], variable: '--bebas-neue', display: 'swap' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();
  return (
    <html lang="en">
      {/* <SessionProvider session={session}> */}
        <body
          className={`
            ${inter.className}
            ${bebas.variable}
            antialiased 
            flex 
            flex-col 
            h-screen 
            justify-between
          `}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      {/* </SessionProvider> */}
    </html>
  );
}
